

def change(a):
    m=[]
    x=int(input("Enter value you want to replace:"))
    y=int(input("Enter value you want to change with:"))
    for i in a:
        if x==i:
            m.append(c)
        else:
            m.append(i)    
    print(m)

def createlist():
    c=[]
    y=int(input("How many numbers you want to enter in list:"))
    for i in range(y):
        d=int(input("Enter a number:"))
        n.append(d)
    change(n)

createlist()